name: data_classification_app
channels:
  - snowflake
dependencies:
  - python=3.11
  - streamlit
  - snowflake-snowpark-python
  - snowflake-connector-python
  - pandas
  - numpy
  - pydantic
  - cryptography
  - authlib
  - sqlalchemy
  - requests
  - pyarrow
  - plotly
  - altair
  - python-dateutil
  - pytz
