name: data_governance_app
channels:
  - snowflake
dependencies:
  - python=3.9
  - streamlit
  - snowflake-snowpark-python
  - snowflake-connector-python
  - pandas
  - numpy
  - pydantic
  - pydantic-settings
  - cryptography
  - plotly
  - altair
  - requests
