name: data_governance_app
channels:
  - snowflake
dependencies:
  - python=3.11
  - streamlit=1.35.0
  - snowflake-snowpark-python=1.37.0
  - pandas=2.1.4
  - numpy=1.26.4
  - pydantic=2.5.2
  - pydantic-settings=2.1.0
  - cryptography=41.0.7
  - plotly=5.18.0
  - altair=5.2.0
  - requests=2.31.0
  - authlib=1.3.0
